# Generated by Django 4.1.5 on 2023-02-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Tarmoq', 'verbose_name_plural': 'Tarmoqlar'},
        ),
    ]
