# Generated by Django 4.0.6 on 2023-02-14 06:14

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kategoriya tarifi')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Kategoriya tarifi')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Kategoriya tarifi')),
                ('image', models.ImageField(upload_to='category-image', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subkategoriya nomi')),
                ('image', models.ImageField(upload_to='subcategory-images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'SubKategoriya',
                'verbose_name_plural': 'SubKategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='nomi')),
                ('price', models.FloatField(default=0, verbose_name='narxi')),
                ('description', models.TextField(verbose_name="Ta'rifi")),
                ('description_uz', models.TextField(null=True, verbose_name="Ta'rifi")),
                ('description_ru', models.TextField(null=True, verbose_name="Ta'rifi")),
                ('characteristic', models.TextField(null=True, verbose_name='Xarakteristikasi')),
                ('characteristic_uz', models.TextField(null=True, verbose_name='Xarakteristikasi')),
                ('characteristic_ru', models.TextField(null=True, verbose_name='Xarakteristikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=150, upload_to=shop.models.rename_product_image, verbose_name='rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Maxsulot')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
    ]
