# Generated by Django 4.1.5 on 2023-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='xarakteristika',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.TextField(null=True, verbose_name='xarakteristikasi'),
        ),
    ]
