# Generated by Django 4.1.5 on 2023-02-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic_ru',
            field=models.TextField(null=True, verbose_name='Xarakteristikasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_uz',
            field=models.TextField(null=True, verbose_name='Xarakteristikasi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category-image', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.TextField(null=True, verbose_name='Xarakteristikasi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name="Ta'rifi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name="Ta'rifi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name="Ta'rifi"),
        ),
    ]
