# Generated by Django 4.1.5 on 2023-02-14 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subcategory_name_ru_subcategory_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='video_file',
            field=models.FileField(default=' ', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.mp4', '.avi', '.wmv', '.mov'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory', verbose_name='Kategoriya'),
        ),
    ]
