# Generated by Django 4.1.5 on 2023-02-14 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_video_file_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.mp4', '.avi', '.wmv', '.mov'])]),
        ),
    ]
