# Generated by Django 4.1.5 on 2023-02-16 05:36

import django.core.validators
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='value',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[("so'm", "so'm"), ('$', '$')], default="so'm", max_length=7, verbose_name='Valyutasi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', '.avi', '.wmv', '.mov'])]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text="Tavsiya etiladiogan rasm o'lchani 719x791", max_length=150, upload_to=shop.models.rename_product_image, verbose_name='rasm'),
        ),
    ]
