# Generated by Django 4.1.5 on 2023-02-17 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_price_product_value_product_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='media',
            field=models.CharField(default='Image', help_text='Asosiy sahifada rasm yoki video turishini tanlash', max_length=10, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[("so'm", "So'm"), ('$', 'Dollar')], default="so'm", max_length=7, verbose_name='Valyutasi'),
        ),
    ]
