# Generated by Django 4.1.5 on 2023-02-22 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_media_alter_category_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field=1105, upload_to='settings/', verbose_name='Bosh mahsulotlar pastki qismidan chiqadigan rasm', width_field=2533)),
                ('is_active', models.BooleanField(default=False, verbose_name='Activligi')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text="rasm o'lchami 1920x1080 nisbatda bo'lishi kerak", upload_to='category-image', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='category',
            name='media',
            field=models.CharField(choices=[('Video', 'Video'), ('Image', 'Image')], default='Image', help_text='Asosiy sahifada rasm yoki video turishini tanlash', max_length=10, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video_file',
            field=models.FileField(blank=True, help_text="Video o'lchami 1920x1080 nisbatda bo'lishi kerak", null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
