# Generated by Django 4.1.5 on 2023-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_homepageimages_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='media',
        ),
        migrations.RemoveField(
            model_name='category',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text="rasm o'lchami 2533x1105 nisbatda bo'lishi kerak", upload_to='category-image', verbose_name='Rasm'),
        ),
    ]
