# Generated by Django 4.1.5 on 2023-02-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_category_media_remove_category_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageimages',
            name='is_active',
        ),
        migrations.AddField(
            model_name='homepageimages',
            name='caption_text',
            field=models.CharField(default=1, help_text='Fashion Collections', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageimages',
            name='date_text',
            field=models.CharField(default=1, help_text='Summer 2020', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageimages',
            name='description_text',
            field=models.TextField(default=1, help_text='Lorem ipsum dolor sit amet'),
            preserve_default=False,
        ),
    ]
