# Generated by Django 4.1.5 on 2023-02-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_homepageimages_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageimages',
            options={'verbose_name': 'Bosh sahifa', 'verbose_name_plural': 'Bosh sahifa'},
        ),
        migrations.AlterField(
            model_name='homepageimages',
            name='img',
            field=models.ImageField(upload_to='settings/', verbose_name='Carusel fon chiqadigan rasm'),
        ),
    ]
