# Generated by Django 4.1.5 on 2023-02-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Texnik hususiyatlar', 'verbose_name_plural': 'Texnik hususiyatlar'},
        ),
    ]
