# Generated by Django 4.1.5 on 2023-02-25 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_characteristic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.TextField(null=True, verbose_name='Xarakteristikasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_ru',
            field=models.TextField(null=True, verbose_name='Xarakteristikasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_uz',
            field=models.TextField(null=True, verbose_name='Xarakteristikasi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory', verbose_name='Kategoriya'),
        ),
    ]
