# Generated by Django 4.1.5 on 2023-03-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text="rasm o'lchami 2533x1105 nisbatda bo'lishi kerak", upload_to='category-image/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text="Tavsiya etiladiogan rasm o'lchani 719x791", max_length=150, upload_to='product/%Y/%m/%d/', verbose_name='rasm'),
        ),
    ]
