# Generated by Django 4.1.5 on 2023-03-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Kategoriya'),
            preserve_default=False,
        ),
    ]
