# Generated by Django 4.1.5 on 2023-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimages',
            name='caption_text',
            field=models.CharField(default='', help_text='Fashion Collections', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepageimages',
            name='date_text',
            field=models.CharField(default='', help_text='Summer 2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepageimages',
            name='description_text',
            field=models.TextField(default='', help_text='Lorem ipsum dolor sit amet'),
        ),
    ]
